# Generated by Django 5.2.8 on 2025-11-10 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('tarot_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='love_readings', to='reading.tarotcard')),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('tarot_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_readings', to='reading.tarotcard')),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('tarot_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_readings', to='reading.tarotcard')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('tarot_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_readings', to='reading.tarotcard')),
            ],
        ),
    ]
